name: Ethereum Bot

on:
  schedule:
    - cron: '0 6,10,14,18 * * *'  # 08:00, 12:00, 16:00, 20:00 Polish time (UTC +2)
  workflow_dispatch:

jobs:
  run-ethbot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETH bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
        run: python main.py --cli
